### ISSUE TITLE
FontSizeOption value set multiple times

### ISSUE THREAD

**Issue by shubham303** [mineshmathew/UnicodeFonts_IndicScripts#1]
`fontSizeOptions={'12','14','16','18','20','22','24','26','28','32','34','36'}
fontSizeOptions={'44','46','56','58','66','72'}
`

At line number 66, is this a mistake in code ? You have changed value of fontsizeOptions.

**Comment by mineshmathew** [comment]
I think I used the font sizes in the second assignment . These are just rendering choices you may use the sizes you prefer
